import Footer from "@/components/Footer";
import Head from "next/head";

function Layouts({ title, children }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <Footer />
    </div>
  );
}

export default Layouts;

Layouts.defaultProps = {
  title: "Create Next App",
};
